### ISSUE TITLE
How to resolve memory out-of-bounds issues?

### ISSUE THREAD

**Issue by BearBiscuit05** [SNU-ARC/Ginex#5]
Hello, it seems that I've encountered a memory out-of-bounds issue when using my dataset(UK-2006). I'm not entirely sure how this problem arises, and it could be related to the settings of certain parameters. As I couldn't find guidance on how to properly set these parameters(like neigh-cache-size or feature-cache-size), I have been conducting experiments with the default parameter settings. Here is the error message I'm encountering. I would like to know how to resolve the issue.
```
Epoch 00:   0%|                                                                                                                                                                                | 0/777410 [00:00<?, ?it/s]double free or corruption (!prev)
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
corrupted size vs. prev_size
corrupted size vs. prev_size
corrupted size vs. prev_size
ERROR: Unexpected segmentation fault encountered in worker.
double free or corruption (!prev)
^CTraceback (most recent call last):
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_ginex.py", line 410, in <module>
    loss, acc = train(epoch)
  File "run_ginex.py", line 303, in train
    cache, initial_cache_indices  = inspect(i, last=(i==num_sb), mode='train')
  File "run_ginex.py", line 118, in inspect
    for step, _ in enumerate(loader):
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/bear/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by hirayaku** [comment]
I found increasing the neighbor buffer size in the sampler implementation effective in avoiding the segfault. Specifically, update [this line](https://github.com/SNU-ARC/Ginex/blob/fc2c085ad3406508dcf1dc3d750c8d24fb3b17cb/lib/cpp_extension/sample.cpp#L45) to 
```cpp
int64_t neighbor_buffer_size = 1<<20; // the original value is 1<<15
```
